# Generated by Django 4.1.2 on 2022-10-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackUsername', models.CharField(blank=True, max_length=100, null=True)),
                ('backend', models.BooleanField()),
                ('age', models.IntegerField()),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
