# Generated by Django 4.1.2 on 2022-10-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='UserInfo',
        ),
    ]
